title: Address Book Inquiry
author: Finnur Bragason
email: fbragason@outlook.com
description: > # this means to ignore newlines until "twitter_username:"
  An Oracle E1 Page Template  

aux_links:
  "Github":
  - "//github.com/Herdubreid/e1p-ab-inquiry"

remote_theme: pmarsceill/just-the-docs
